version: "3.9"


services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: flask_hw
    ports:
      - "5432:5432"
